feat: add auth client and generate_disposable_token api
momentohq/client-sdk-rust pull request #420
Opened 2024-12-19 20:20 UTC by anitarua

2024-12-21 14:01 UTC, benbpyle commented
Thanks for implementing this feature!

2025-01-01 02:12 UTC, honeyAcorn requested changes

2025-01-01 02:13 UTC, honeyAcorn commented
I've verified the capability by using momento console to generate superuser api key.
Then use the Superuser API key to generate disposable token using rust sdk.
Those disposable token can only be used toward certain cache for only read or write or both.
Everything looks good except for some missing test case.
1. prefix-write
2. Can we add a verify for the expire time? Add one case to expire in a few seconds and test if it expires in integration test.

2025-01-03 17:30 UTC, honeyAcorn approved these changes
LGTM!

2025-01-03 18:32 UTC, pgautier404 approved these changes

2025-01-03 18:42 UTC, merged